// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPKiXrPqW2EOrV-8wV8yaXuW9cujBRkkM',
    appId: '1:694148158830:web:57be2240cb3d0fee2b1d7f',
    messagingSenderId: '694148158830',
    projectId: 'crud-f5da6',
    authDomain: 'crud-f5da6.firebaseapp.com',
    storageBucket: 'crud-f5da6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXcCtfAkfx8fnkI-8wW34geBekb1Cuoo',
    appId: '1:694148158830:android:0936783b7debcca12b1d7f',
    messagingSenderId: '694148158830',
    projectId: 'crud-f5da6',
    storageBucket: 'crud-f5da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBreL5aWTLr6sVlpdvWdCkE7vfQYStLQ1Q',
    appId: '1:694148158830:ios:92f49d7d7741738e2b1d7f',
    messagingSenderId: '694148158830',
    projectId: 'crud-f5da6',
    storageBucket: 'crud-f5da6.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBreL5aWTLr6sVlpdvWdCkE7vfQYStLQ1Q',
    appId: '1:694148158830:ios:92f49d7d7741738e2b1d7f',
    messagingSenderId: '694148158830',
    projectId: 'crud-f5da6',
    storageBucket: 'crud-f5da6.appspot.com',
    iosBundleId: 'com.example.crud',
  );
}
